packages:
  - examples/*
  - migration/*
  - packages/*

overrides:
  cookie@<0.7.0: '>=0.7.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@=4.0.0: '>=4.0.1'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  vite@>=7.0.0 <=7.0.6: '>=7.0.7'
  vite@>=7.0.0 <=7.0.7: '>=7.0.8'
