packages:
  - examples/*
  - migration/*
  - packages/*

overrides:
  cookie@<0.7.0: '>=0.7.0'
  undici@<5.29.0: '>=5.29.0'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  vite@>=7.0.0 <=7.0.6: '>=7.0.7'
  vite@>=7.0.0 <=7.0.7: '>=7.0.8'
